'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
import SideBar from './components/SibeBar'
import { usePathname } from 'next/navigation';
import { Navigate, Outlet } from "react-router-dom";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
const authPaths =['/auth/login','/auth/register','/auth/forgotpassword']
  return (
    <html lang="en">
      <body className='flex flex-row'>
        <Providers>
          {!authPaths.includes(pathname) && <SideBar/>}

          {children}
          </Providers>
      </body>
   
    </html>
  )
}
