import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
import SideBar from './components/SibeBar'
import { usePathname } from 'next/navigation';
import { Navigate, Outlet } from "react-router-dom";
import {BrowserRouter as Router} from 'react-router-dom';
import ToasterProvider from './providers/ToasterProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname : string|null = usePathname();
const authPaths:Array<string|null> =['/auth/login','/auth/register','/auth/forgotpassword','/auth/newpassword','/auth/verify']
  return (
    <Router>

    <html lang="en">
      <body className='flex flex-row'>
        <Providers>
        <ToasterProvider />

          {!authPaths.includes(pathname) &&   <SideBar/> }

          {children}
          </Providers>
      </body>
   
    </html>
    </Router>
  )
}
